server:
  port: 8081

spring:
  servlet:
    multipart:
      max-file-size: "10MB"
      max-request-size: "10MB"

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /doc.html
    operations-sorter: method
    tags-sorter: alpha
    display-request-duration: true